name: PHP Composer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor

      - name: Install Composer Packages
        run: composer install -vvv

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
